networks:
  project:
    driver: bridge
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend 
    networks:
      - project
  
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:80"
    networks:
      - project
  
  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - project
    depends_on: 
      - db
  
  db:
    container_name: postgres_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - project
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
    db-data: